FROM node:alpine as builder
WORKDIR '/usr/reactProject/frontend'
COPY ./package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
COPY --from=builder /usr/reactProject/frontend /usr/share/nginx/html